// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: deal.sql

package model

import (
	"context"
)

const getDeal = `-- name: GetDeal :one
SELECT deal_id, author, store_name, description, regular_price, sale_price, upvote, create_time FROM deal
WHERE deal_id = $1 LIMIT 1
`

func (q *Queries) GetDeal(ctx context.Context, dealID int64) (Deal, error) {
	row := q.db.QueryRowContext(ctx, getDeal, dealID)
	var i Deal
	err := row.Scan(
		&i.DealID,
		&i.Author,
		&i.StoreName,
		&i.Description,
		&i.RegularPrice,
		&i.SalePrice,
		&i.Upvote,
		&i.CreateTime,
	)
	return i, err
}
